apiVersion: v1
kind: Service
metadata:
  name: transformation
spec:
  selector:
    app: transformation
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30000
  type: NodePort
